Omni   1000 new branch
omni-srejitk/SPOTLIGHT-VITE pull request #2
Opened 2022-12-06 12:19 UTC by naresh130199

updated the code

2022-12-06 12:32 UTC, omni-srejitk requested changes
Remove unnecessary blocks of console logs
and setup prettier + linting to  enhance code readability .

2022-12-06 12:32 UTC, omni-srejitk commented on src/App.jsx
> +// return <RouterConfig />;
Remove this.

2022-12-06 12:32 UTC, omni-srejitk commented on src/Brands/Brand.jsx
> +  console.log("pathName", pathName);
Remove this log

2022-12-06 12:32 UTC, omni-srejitk commented on src/components/MainButton.jsx
> +            <img className=" w-[100%] h-[100%]" src={data.brandLogo} alt="/" />
use w-full, h-full instead of hard coding 100%. Inline styles with custom values leads to additional CSS calculations

2022-12-06 12:32 UTC, omni-srejitk commented on src/components/MainButton.jsx
> +          <div className=" w-[64px] h-[64px] rounded-[32px]">
Same here. Use in built Tailwind utils before moving to custom values

2022-12-06 12:32 UTC, omni-srejitk commented on src/components/MainButton.jsx
> +          console.log("user", user);
Remove these logs

2022-12-06 12:32 UTC, omni-srejitk commented on src/components/NewStoreNotFoundCard.jsx
> +              </button> */}
Remove these comments

2022-12-06 12:32 UTC, omni-srejitk commented on src/conditions/iflocationallow/brandsStore/BrandStores.jsx
> +  console.log("apiValue", apiValue);
Remove logs

2022-12-06 12:32 UTC, omni-srejitk commented on src/config/RouterConfig.jsx
> +            {/* </Route> */}
Remove this

2022-12-06 12:33 UTC, naresh130199 commented on src/components/NewStoreNotFoundCard.jsx
> +              </button> */}
okay

2022-12-06 12:34 UTC, naresh130199 commented on src/components/MainButton.jsx
> +            <img className=" w-[100%] h-[100%]" src={data.brandLogo} alt="/" />
will remember this

2022-12-07 06:55 UTC, naresh130199 commented on src/config/RouterConfig.jsx
> +            {/* </Route> */}
done

2022-12-20 07:29 UTC, omni-srejitk requested changes
Have suggested a few minor changes. Have a look into it. 
Good work otherwise.

2022-12-20 07:29 UTC, omni-srejitk commented on src/Home/Home.jsx
> +          navigate(encodeURI("/Beyondarie"));
Let's not hardcode this and make it dynamic. Let's access it from the search params

2022-12-20 07:29 UTC, omni-srejitk commented on src/components/MainButton.jsx
> +          // Todo what about 93% and negative padding?
Is this addressed? The 93% and negative padding part?

2022-12-20 07:29 UTC, omni-srejitk commented on src/components/SplashColors.jsx
> +// import SplashColorsAnimation from "../Loading/SplashColors.json";
These are required?

2022-12-20 07:51 UTC, omni-srejitk approved these changes

2022-12-20 07:51 UTC, merged